(define (reverse l)
  (if (equal? '() l)
     '()
     (append (reverse (cdr l)) (list (car l)))
  )
)
(define (deep-reverse l)
  (if (equal? '() l)
     '()
     (append  (deep-reverse (reverse (cdr l))) (list (reverse (car l))))
  ))